// apps/react/src/components/input/C1Input.tsx
import { useMemo, useRef } from 'react';
import { C1IconInformationStroke } from '@rei/c1-icons/react';
import { useInputAdapter } from '@rei/c1-ui/adapters/input/react';

import type {
  C1InputProps,
  ErrorBlockProps,
  InputAdapterState,
} from './C1Input.types';
import type {
  ChangeEventHandler,
  InputHTMLAttributes,
  RefObject,
  TextareaHTMLAttributes,
} from 'react';

const cx = (...values: Array<string | false | null | undefined>) =>
  values.filter(Boolean).join(' ');

const ErrorBlock = ({
  showError,
  errorId,
  errorRole,
  message,
}: ErrorBlockProps) => (
  <div
    className={cx('cdr-form-error', showError && '--active-error')}
    id={errorId}
  >
    <span
      className="cdr-form-error__icon"
      style={{ display: showError ? 'inline-flex' : 'none' }}
    >
      <C1IconInformationStroke
        aria-hidden="true"
        focusable={false}
        inheritColor
      />
    </span>
    <div role={errorRole} aria-atomic="true" aria-relevant="all">
      {showError ? <div>{message}</div> : null}
    </div>
  </div>
);

const C1Input = ({
  id,
  type = 'text',
  label,
  numeric = false,
  hideLabel = false,
  rows = 1,
  background = 'primary',
  size,
  errorRole = 'status',
  error = false,
  disabled = false,
  required = false,
  optional = false,
  postIcons = false,
  inputContainerClass,
  labelClass,
  modelValue,
  onUpdateModelValue,
  slots,
}: C1InputProps) => {
  const inputRef = useRef<HTMLInputElement | HTMLTextAreaElement | null>(null);
  const {
    'helper-text-top': helperTextTop,
    'helper-text-bottom': helperTextBottom,
    'pre-icon': preIcon,
    'post-icon': postIcon,
    info,
    'info-action': infoAction,
    error: errorSlot,
  } = slots ?? {};
  const flags = {
    hasHelperTop: Boolean(helperTextTop),
    hasHelperBottom: Boolean(helperTextBottom),
    hasPreIcon: Boolean(preIcon),
    hasPostIcon: Boolean(postIcon),
    hasInfo: Boolean(info),
    hasInfoAction: Boolean(infoAction),
  };
  const isMultiline = rows > 1;
  const showError = Boolean(error);
  const resolvedErrorMessage =
    errorSlot ?? (typeof error === 'string' ? error : undefined);

  const state = useMemo<InputAdapterState>(
    () => ({
      id,
      type,
      numeric,
      rows,
      background,
      size,
      error,
      required,
      optional,
      hasHelperTop: flags.hasHelperTop,
      hasHelperBottom: flags.hasHelperBottom,
      hasPreIcon: flags.hasPreIcon,
      hasPostIcon: flags.hasPostIcon,
      hasPostIcons: postIcons,
    }),
    [
      id,
      type,
      numeric,
      rows,
      background,
      size,
      error,
      required,
      optional,
      flags,
      postIcons,
    ],
  );

  const {
    inputAttrs,
    inputClasses,
    wrapClasses,
    helperTopId,
    helperBottomId,
    errorId,
    onFocus: adapterOnFocus,
    onBlur: adapterOnBlur,
  } = useInputAdapter({
    state,
    inputRef,
  });

  const rootClasses = cx('cdr-label-standalone', inputContainerClass);

  const labelClasses = cx(
    'cdr-label-standalone__label',
    disabled && 'cdr-label-standalone__label--disabled',
    hideLabel && 'cdr-label-standalone__label--sr-only',
    labelClass,
  );

  const baseAttrs = {
    ...inputAttrs,
    autoComplete: 'off',
    disabled: disabled || undefined,
  } as InputHTMLAttributes<HTMLInputElement>;
  const textareaBaseAttrs = {
    ...baseAttrs,
  } as TextareaHTMLAttributes<HTMLTextAreaElement>;
  delete (textareaBaseAttrs as { type?: string }).type;

  const handleChange: ChangeEventHandler<
    HTMLInputElement | HTMLTextAreaElement
  > = (event) => {
    onUpdateModelValue?.(event.target.value);
  };

  const sharedProps = {
    className: inputClasses.join(' '),
    onFocus: adapterOnFocus,
    onBlur: adapterOnBlur,
    onChange: handleChange,
  };

  return (
    <div className={rootClasses}>
      <div className="cdr-label-standalone__label-wrapper">
        <label className={labelClasses} htmlFor={inputAttrs.id}>
          {label}
          {required ? <span aria-hidden="true">*</span> : null}
          {!required && optional ? (
            <span className="cdr-label-standalone__optional">(optional)</span>
          ) : null}
        </label>
        {!hideLabel && flags.hasHelperTop ? <br /> : null}
        {flags.hasHelperTop ? (
          <span className="cdr-label-standalone__helper" id={helperTopId}>
            {helperTextTop}
          </span>
        ) : null}
      </div>

      <div
        className={cx(
          'cdr-label-standalone__input-wrap',
          (!hideLabel || flags.hasHelperTop || flags.hasInfo) &&
            'cdr-label-standalone__input-spacing',
        )}
      >
        <div className={wrapClasses.join(' ')}>
          {isMultiline ? (
            <textarea
              ref={inputRef as RefObject<HTMLTextAreaElement>}
              {...(textareaBaseAttrs as TextareaHTMLAttributes<HTMLTextAreaElement>)}
              {...sharedProps}
              rows={rows}
              {...(modelValue !== undefined ? { value: modelValue } : {})}
            />
          ) : (
            <input
              ref={inputRef as RefObject<HTMLInputElement>}
              {...baseAttrs}
              {...sharedProps}
              type={type}
              {...(modelValue !== undefined ? { value: modelValue } : {})}
            />
          )}
          {flags.hasPreIcon ? (
            <span className="cdr-input__pre-icon">{preIcon}</span>
          ) : null}
          {flags.hasPostIcon ? (
            <span className="cdr-input__post-icon">{postIcon}</span>
          ) : null}
        </div>
        {flags.hasInfoAction ? (
          <div className="cdr-label-standalone__info-action">{infoAction}</div>
        ) : null}
      </div>

      {flags.hasInfo ? (
        <span className="cdr-label-standalone__info">{info}</span>
      ) : null}

      <div className="cdr-label-standalone__post-content">
        {flags.hasHelperBottom && !showError ? (
          <span className="cdr-input__helper-text" id={helperBottomId}>
            {helperTextBottom}
          </span>
        ) : null}
        <ErrorBlock
          showError={showError}
          errorId={errorId}
          errorRole={errorRole}
          message={resolvedErrorMessage}
        />
      </div>
    </div>
  );
};

export default C1Input;
export type { C1InputProps };

// apps/vue/src/components/input/C1Input.vue
<template>
  <div :class="rootClasses">
    <div class="cdr-label-standalone__label-wrapper">
      <label :class="labelClasses" :for="inputAttrs.id">
        {{ label }}
        <span v-if="required" aria-hidden="true">*</span>
        <span v-else-if="optional" class="cdr-label-standalone__optional"
          >(optional)</span
        >
      </label>
      <br v-if="!hideLabel && hasHelperTop" />
      <span
        v-if="hasHelperTop"
        class="cdr-label-standalone__helper"
        :id="helperTopId"
      >
        <slot name="helper-text-top" />
      </span>
    </div>

    <div :class="['cdr-label-standalone__input-wrap', inputSpacingClass]">
      <div :class="wrapClasses">
        <textarea
          v-if="isMultiline"
          ref="inputRef"
          v-bind="textareaAttrs"
          :class="inputClasses"
          :rows="rows"
          @focus="onFocus"
          @blur="onBlur"
          v-model="inputModel"
        ></textarea>
        <input
          v-else
          ref="inputRef"
          v-bind="inputBaseAttrs"
          :class="inputClasses"
          @focus="onFocus"
          @blur="onBlur"
          v-model="inputModel"
        />
        <span v-if="hasPreIcon" class="cdr-input__pre-icon">
          <slot name="pre-icon" />
        </span>
        <span v-if="hasPostIcon" class="cdr-input__post-icon">
          <slot name="post-icon" />
        </span>
      </div>
      <div v-if="hasInfoAction" class="cdr-label-standalone__info-action">
        <slot name="info-action" />
      </div>
    </div>

    <span v-if="hasInfo" class="cdr-label-standalone__info">
      <slot name="info" />
    </span>

    <div class="cdr-label-standalone__post-content">
      <span
        v-if="hasHelperBottom && !showError"
        class="cdr-input__helper-text"
        :id="helperBottomId"
      >
        <slot name="helper-text-bottom" />
      </span>
      <div
        :class="['cdr-form-error', showError ? '--active-error' : '']"
        :id="errorId"
      >
        <span v-show="showError" class="cdr-form-error__icon">
          <C1IconInformationStroke
            aria-hidden="true"
            focusable="false"
            inherit-color
          />
        </span>
        <div :role="errorRole" aria-atomic="true" aria-relevant="all">
          <div v-if="showError">
            <slot name="error">{{ errorMessage }}</slot>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { C1IconInformationStroke } from '@rei/c1-icons/vue';
import { computed, ref, useAttrs, useSlots } from 'vue';

import { useInputAdapter } from '@rei/c1-ui/adapters/input/vue';
import { c1InputProps, type InputAdapterState } from './C1Input.types';

defineOptions({
  name: 'C1Input',
  inheritAttrs: false,
});

const props = defineProps(c1InputProps);

const emit = defineEmits({
  'update:modelValue': null,
});

const slots = useSlots();
const attrs = useAttrs();
const inputRef = ref<HTMLInputElement | HTMLTextAreaElement | null>(null);

const hasHelperTop = computed(() => Boolean(slots['helper-text-top']));
const hasHelperBottom = computed(() => Boolean(slots['helper-text-bottom']));
const hasPreIcon = computed(() => Boolean(slots['pre-icon']));
const hasPostIcon = computed(() => Boolean(slots['post-icon']));
const hasPostIcons = computed(() => props.postIcons && hasPostIcon.value);
const hasInfo = computed(() => Boolean(slots.info));
const hasInfoAction = computed(() => Boolean(slots['info-action']));
const isMultiline = computed(() => props.rows > 1);

const inputSpacingClass = computed(() =>
  !props.hideLabel || hasHelperTop.value || hasInfo.value
    ? 'cdr-label-standalone__input-spacing'
    : '',
);

const rootClasses = computed(() =>
  ['cdr-label-standalone', props.inputContainerClass].filter(Boolean).join(' '),
);

const labelClasses = computed(() =>
  [
    'cdr-label-standalone__label',
    props.disabled ? 'cdr-label-standalone__label--disabled' : '',
    props.hideLabel ? 'cdr-label-standalone__label--sr-only' : '',
    props.labelClass,
  ]
    .filter(Boolean)
    .join(' '),
);

const state = computed<InputAdapterState>(() => ({
  id: props.id,
  type: props.type,
  numeric: props.numeric,
  rows: props.rows,
  background: props.background,
  size: props.size,
  error: props.error,
  required: props.required,
  optional: props.optional,
  hasHelperTop: hasHelperTop.value,
  hasHelperBottom: hasHelperBottom.value,
  hasPreIcon: hasPreIcon.value,
  hasPostIcon: hasPostIcon.value,
  hasPostIcons: hasPostIcons.value,
  describedBy: attrs['aria-describedby'] as string | undefined,
}));

const {
  inputAttrs,
  inputClasses,
  wrapClasses,
  helperTopId,
  helperBottomId,
  errorId,
  onFocus,
  onBlur,
} = useInputAdapter({
  state,
  inputRef,
});

const inputBaseAttrs = computed(() => ({
  ...attrs,
  ...inputAttrs.value,
  autocomplete: 'off',
  disabled: props.disabled || undefined,
}));

const textareaAttrs = computed(() => {
  const nextAttrs = { ...inputBaseAttrs.value } as Record<string, unknown>;
  delete nextAttrs.type;
  return nextAttrs;
});

const showError = computed(() => Boolean(props.error));
const errorMessage = computed(() =>
  typeof props.error === 'string' ? props.error : '',
);

const inputModel = computed({
  get: () => props.modelValue,
  set: (value) => emit('update:modelValue', value),
});
</script>
