// apps/vue/src/components/accordion/C1Accordion.vue
<template>
  <div ref="rootRef" :class="rootClasses">
    <component :is="headingTag" ref="headerRef" :class="headerClass">
      <component
        :is="triggerTag"
        ref="triggerRef"
        :type="triggerType"
        :class="triggerClass"
        v-bind="triggerAttrs"
      >
        <span ref="labelRef" class="cdr-accordion__label" v-bind="labelAttrs">
          <slot name="label">{{ label }}</slot>
        </span>
        <span
          v-if="!isUnwrapped"
          ref="iconRef"
          :class="iconClasses"
          aria-hidden="true"
        >
          <C1IconCaretDown
            aria-hidden="true"
            focusable="false"
            inherit-color
            :size="compact ? 'small' : undefined"
          />
        </span>
      </component>
    </component>

    <div ref="contentContainerRef" :class="containerClasses">
      <div ref="contentRef" :class="contentClasses" v-bind="contentAttrs">
        <slot />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, inject, ref } from 'vue';
import { C1IconCaretDown } from '@rei/c1-icons/vue';
import { useAccordionAdapter } from '@rei/c1-ui/adapters/accordion/vue';
import {
  c1AccordionProps,
  type AccordionAdapterState,
} from './C1Accordion.types';
import { accordionUnwrapKey } from './accordionContext';

defineOptions({
  name: 'C1Accordion',
});

const props = defineProps(c1AccordionProps);

const emit = defineEmits({
  'accordion-toggle': null,
});

const rootRef = ref<HTMLElement | null>(null);
const headerRef = ref<HTMLElement | null>(null);
const triggerRef = ref<HTMLElement | null>(null);
const labelRef = ref<HTMLElement | null>(null);
const iconRef = ref<HTMLElement | null>(null);
const contentContainerRef = ref<HTMLElement | null>(null);
const contentRef = ref<HTMLElement | null>(null);

const injectedUnwrap = inject(accordionUnwrapKey, ref(false));
const isUnwrapped = computed(() => injectedUnwrap.value);
const isOpen = computed(() => props.opened || isUnwrapped.value);
const headingTag = computed(() => `h${props.level}`);
const headerClass = computed(() =>
  isUnwrapped.value
    ? 'cdr-accordion__header--unwrapped'
    : 'cdr-accordion__header',
);
const triggerTag = computed(() => (isUnwrapped.value ? 'div' : 'button'));
const triggerType = computed(() => (isUnwrapped.value ? undefined : 'button'));
const triggerClass = computed(() =>
  isUnwrapped.value
    ? 'js-cdr-accordion-button'
    : 'cdr-accordion__button js-cdr-accordion-button',
);

const rootClasses = computed(() =>
  [
    'cdr-accordion',
    props.compact && 'cdr-accordion--compact',
    props.borderAligned && 'cdr-accordion--border-aligned',
    !props.contentSpacing && 'cdr-accordion--no-spacing',
    isUnwrapped.value && 'cdr-accordion--unwrap',
  ]
    .filter(Boolean)
    .join(' '),
);

const iconClasses = computed(() =>
  [
    'cdr-accordion__icon',
    isOpen.value ? 'cdr-accordion--open' : 'cdr-accordion--closed',
  ]
    .filter(Boolean)
    .join(' '),
);

const containerClasses = computed(() =>
  [
    'cdr-accordion__content-container',
    isOpen.value ? 'cdr-accordion--open' : 'cdr-accordion--closed',
    isUnwrapped.value && 'cdr-accordion--unwrap',
  ]
    .filter(Boolean)
    .join(' '),
);

const contentClasses = computed(() =>
  [
    'cdr-accordion__content',
    isOpen.value ? 'cdr-accordion--open' : 'cdr-accordion--closed',
    isUnwrapped.value && 'cdr-accordion--unwrap',
  ]
    .filter(Boolean)
    .join(' '),
);

const triggerAttrs = computed(() => ({
  id: props.id,
  'aria-expanded': !isUnwrapped.value ? props.opened : undefined,
  'aria-controls': !isUnwrapped.value ? `${props.id}-collapsible` : undefined,
}));

const labelAttrs = computed(() => ({
  id: `${props.id}-label`,
}));

const contentAttrs = computed(() => ({
  id: `${props.id}-collapsible`,
  'aria-hidden': !isUnwrapped.value ? !props.opened : undefined,
}));

const state = computed<AccordionAdapterState>(() => ({
  id: props.id,
  opened: props.opened,
  unwrapped: isUnwrapped.value,
}));

useAccordionAdapter({
  refs: {
    root: rootRef,
    header: headerRef,
    trigger: triggerRef,
    label: labelRef,
    icon: iconRef,
    contentContainer: contentContainerRef,
    content: contentRef,
  },
  state,
  adapterOptions: {
    autoToggle: false,
    onToggle: (_nextOpen: boolean, event: Event) =>
      emit('accordion-toggle', event),
  },
});
</script>

// apps/react/src/components/accordion/C1Accordion.tsx
import { useEffect, useMemo, useRef, createElement } from 'react';
import { C1IconCaretDown } from '@rei/c1-icons/react';
import { useAccordionAdapter } from '@rei/c1-ui/adapters/accordion/react';

import type {
  C1AccordionProps,
  AccordionAdapterState,
} from './C1Accordion.types';
import { useAccordionUnwrap } from './accordionContext';

const cx = (...values: Array<string | false | null | undefined>) =>
  values.filter(Boolean).join(' ');

const C1Accordion = ({
  id,
  opened = false,
  compact = false,
  borderAligned = false,
  contentSpacing = true,
  level,
  label,
  onAccordionToggle,
  children,
}: C1AccordionProps) => {
  const unwrapped = useAccordionUnwrap();
  const rootRef = useRef<HTMLDivElement | null>(null);
  const headerRef = useRef<HTMLElement | null>(null);
  const triggerRef = useRef<HTMLElement | null>(null);
  const labelRef = useRef<HTMLSpanElement | null>(null);
  const iconRef = useRef<HTMLSpanElement | null>(null);
  const contentContainerRef = useRef<HTMLDivElement | null>(null);
  const contentRef = useRef<HTMLDivElement | null>(null);
  const onToggleRef = useRef(onAccordionToggle);

  const state = useMemo<AccordionAdapterState>(
    () => ({
      id,
      opened,
      unwrapped,
    }),
    [id, opened, unwrapped],
  );

  useEffect(() => {
    onToggleRef.current = onAccordionToggle;
  }, [onAccordionToggle]);

  const adapterOptions = useMemo(
    () => ({
      autoToggle: false,
      onToggle: (_nextOpen: boolean, event: Event) => {
        onToggleRef.current?.(event);
      },
    }),
    [],
  );

  const adapterRefs = useMemo(
    () => ({
      root: rootRef,
      header: headerRef,
      trigger: triggerRef,
      label: labelRef,
      icon: iconRef,
      contentContainer: contentContainerRef,
      content: contentRef,
    }),
    [],
  );

  useAccordionAdapter({
    refs: adapterRefs,
    state,
    adapterOptions,
  });

  const isOpen = opened || unwrapped;
  const ariaExpanded = !unwrapped ? opened : undefined;
  const ariaControls = !unwrapped ? `${id}-collapsible` : undefined;
  const ariaHidden = !unwrapped ? !opened : undefined;
  const parsedLevel = Number(level);
  const headingLevel = Number.isFinite(parsedLevel) ? parsedLevel : 3;
  const headingTag = `h${headingLevel}` as
    | 'h1'
    | 'h2'
    | 'h3'
    | 'h4'
    | 'h5'
    | 'h6';

  const setTriggerRef = (node: HTMLElement | null) => {
    triggerRef.current = node;
  };

  return (
    <div
      ref={rootRef}
      className={cx(
        'cdr-accordion',
        compact && 'cdr-accordion--compact',
        borderAligned && 'cdr-accordion--border-aligned',
        !contentSpacing && 'cdr-accordion--no-spacing',
        unwrapped && 'cdr-accordion--unwrap',
      )}
    >
      {createElement(
        headingTag,
        {
          ref: headerRef,
          className: unwrapped
            ? 'cdr-accordion__header--unwrapped'
            : 'cdr-accordion__header',
        },
        unwrapped ? (
          <div ref={setTriggerRef} className="js-cdr-accordion-button" id={id}>
            <span
              ref={labelRef}
              className="cdr-accordion__label"
              id={`${id}-label`}
            >
              {label}
            </span>
          </div>
        ) : (
          <button
            ref={setTriggerRef}
            type="button"
            className="cdr-accordion__button js-cdr-accordion-button"
            id={id}
            aria-expanded={ariaExpanded}
            aria-controls={ariaControls}
          >
            <span
              ref={labelRef}
              className="cdr-accordion__label"
              id={`${id}-label`}
            >
              {label}
            </span>
            <span
              ref={iconRef}
              className={cx(
                'cdr-accordion__icon',
                isOpen ? 'cdr-accordion--open' : 'cdr-accordion--closed',
              )}
              aria-hidden="true"
            >
              <C1IconCaretDown
                aria-hidden="true"
                focusable={false}
                inheritColor
                size={compact ? 'small' : undefined}
              />
            </span>
          </button>
        ),
      )}

      <div
        ref={contentContainerRef}
        className={cx(
          'cdr-accordion__content-container',
          isOpen ? 'cdr-accordion--open' : 'cdr-accordion--closed',
          unwrapped && 'cdr-accordion--unwrap',
        )}
      >
        <div
          ref={contentRef}
          className={cx(
            'cdr-accordion__content',
            isOpen ? 'cdr-accordion--open' : 'cdr-accordion--closed',
            unwrapped && 'cdr-accordion--unwrap',
          )}
          id={`${id}-collapsible`}
          aria-hidden={ariaHidden}
        >
          {children}
        </div>
      </div>
    </div>
  );
};

export default C1Accordion;
